package com.carDealerProject.service;

import com.carDealerProject.repo.InventoryRepo;
import com.carDealerProject.entity.Car;
import com.carDealerProject.entity.Inventory;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


@Service

public class InventoryService {
    @Autowired
    private InventoryRepo inventoryRepo;

    public Inventory save(Inventory inventory) {
		// Another predefined function, used to save your objects
		// Id will be autogenerated and will come back in the return after its saved

	    return inventoryRepo.save(inventory);
	}
	
	public Inventory update(Inventory inventory) throws Exception {
		// Another predefined function, used to save your objects
		// Id will be autogenerated and will come back in the return after its saved

        if(inventory.getId() != null) {
	        return inventoryRepo.save(inventory);
        }

        throw new Exception("Object does not exist! id not present");
	}
    
    public Inventory findById(Integer inventoryId) throws Error {
        
    	// Find by is another predefined repo function, you can always find by the primary key
    	// when you use findById, its good practice to use the isPresent in an if check first
    	// It will tell you if a object was actually found, with true or false values, true if found, false is not
    	// It will always return an Optional Object, the Inventory will be there if found, null if not
    	// If found, give the object back with a .get() to grab it off the Optional object
    	
        if(inventoryRepo.findById(inventoryId).isPresent()) {
            return inventoryRepo.findById(inventoryId).get();
        }
        
        // if Inventory is not present, throw error so front end can handle it
        throw new Error("No Inventory id present, Inventory not found, send an id billy, dumbass");
        
    }

	public List<Inventory> findAll() {
		return inventoryRepo.findAll();
	}

    public void deleteById(Integer id) {
	    inventoryRepo.deleteById(id);
	}

	public Inventory addCarToInventory(Integer inventoryID, Car car){
		Inventory inventory = findById(inventoryID);
		inventory.getCarsInInventory().add(car);
		return inventoryRepo.save(inventory);
	}

    public Inventory removeCarFromInventory(Integer inventoryID, Car car){
        Inventory inventory = findById(inventoryID);
		inventory.getCarsInInventory().remove(car);
		return inventoryRepo.save(inventory);
    }
}
